import { pageMetadata, pageSchema, breadcrumbSchema, organizationId } from '../../seo';
import { StructuredData } from '../../structured-data';
import { notFound, permanentRedirect } from 'next/navigation';
import { SiteHeader, SiteFooter, PageMotion } from '../../new-site';
import { businessWorlds, legacyWorlds } from '../../new-content';
import { Arrow, Icon } from '../../ui';
import { BusinessFlow } from '../../business-flow';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}) {const {slug}=await params;const w=businessWorlds.find(w=>w.slug===slug);return w ? pageMetadata(`/branchen/${slug}`, `Digitalisierung: ${w.name} | Pichler Advisory`, w.description) : {title:'Branchen | Pichler Advisory', robots: { index: false }};}
export default async function IndustryPage({params}:{params:Promise<{slug:string}>}) {
 const {slug}=await params;if(Object.prototype.hasOwnProperty.call(legacyWorlds,slug))permanentRedirect('/branchen/'+legacyWorlds[slug]);const index=businessWorlds.findIndex(w=>w.slug===slug);if(index<0)notFound();const w=businessWorlds[index];
 const path = `/branchen/${slug}`;
 return <><StructuredData data={[{ ...pageSchema(path, w.fullName), about: { '@id': organizationId } }, breadcrumbSchema(path, w.fullName)]} /><PageMotion/><SiteHeader/><main id="inhalt"><section className="world-hero wrap"><a className="breadcrumb" href="/#branchen">Für Ihren Betrieb <span>/</span> {w.name}</a><div className="world-hero-grid"><div><p className="overline">{w.fullName}</p><h1>{w.heading}</h1><p className="service-lead">{w.description}</p><a className="button" href="/#anfrage">Potenzial besprechen <Arrow/></a></div><div className="industry-example industry-flow"><BusinessFlow world={index}/></div></div><p className="world-examples">Für {w.examples.join(' · ')}</p></section><section className="world-needs wrap"><div className="section-heading" data-enter><p className="overline">Der Alltag zeigt, wo es besser geht</p><h2>Hier lohnt sich<br />ein genauer Blick.</h2></div><div className="needs-grid">{w.pains.map((pain,i)=><article key={pain} data-enter><span className="small-number">0{i+1}</span><h3>{pain}</h3><div><Icon name="check"/><p>{w.solutions[i]}</p></div></article>)}</div></section><section className="world-entry"><div className="wrap world-entry-grid"><div><p className="overline">Sie geben die Richtung vor</p><h2>Ein Prozess.<br />Oder der ganze Betrieb.</h2></div><div><p>Sie wissen bereits, wo es hakt? Dann konzentrieren wir uns auf diese Aufgabe. Wenn Sie die Möglichkeiten erst herausfinden möchten, schauen wir uns Ihren Betrieb vor Ort an.</p><p>Auch Apps, Websites und einzelne IT-Projekte setzen wir direkt um — ohne vorgängige Betriebsanalyse.</p><a href={`/leistungen/${w.service}`} className="text-link">Die passende Leistung kennenlernen <Arrow/></a></div></div></section><section className="world-next wrap"><h2>Was soll in Ihrem<br />Betrieb besser laufen?</h2><p>Wir klären den Auftrag, vereinbaren Umfang und Kosten und setzen die Lösung mit Ihnen um.</p><a href="/#anfrage" className="button">Vorhaben besprechen <Arrow/></a></section><section className="related-section wrap"><p className="overline">Weitere Unternehmenswelten</p><div>{businessWorlds.filter(v=>v.slug!==slug).map(v=><a key={v.slug} href={`/branchen/${v.slug}`}>{v.name}<Arrow/></a>)}</div></section></main><SiteFooter/></>;
}
