"use client";
/* eslint-disable @next/next/no-img-element */
import { useState } from 'react';
import { WebsiteShowcase } from './website-showcase';
import { OrderInterface } from './new-site';
import { Arrow, Icon } from './ui';

export function ServiceExample({ slug }: { slug: string }) {
  const [choice, setChoice] = useState(0);
  return <div className={`service-example example-${slug}`}>
    {slug === 'prozesse-automatisierung' ? <><div className="example-toolbar"><span>Ein Auftrag. Zwei mögliche Wege.</span><div className="segmented" role="group" aria-label="Ablauf vergleichen">{['Heute', 'Möglich'].map((s,i) => <button key={s} aria-pressed={choice===i} onClick={() => setChoice(i)}>{s}</button>)}</div></div><div className="workflow-example" key={choice}><h3>{choice ? 'Die Information arbeitet weiter.' : 'Die gleiche Arbeit. Immer wieder.'}</h3><div className="workflow-list">{(choice ? [['Einmal erfassen','Kunde, Auftrag und Leistung an einem Ort.'],['Gemeinsam bearbeiten','Ihr Team hat den aktuellen Stand.'],['Direkt weiterverwenden','Geprüfte Angaben für die Abrechnung.']] : [['E-Mail öffnen','Auftragsdetails in eine Liste übertragen.'],['Angaben zusammensuchen','Nachfragen und Notizen ergänzen.'],['Noch einmal eingeben','Für die Abrechnung erneut übertragen.']]).map(([title,text],i) => <div key={title}><span className={choice ? 'workflow-icon good' : 'workflow-icon'}><Icon name={choice ? 'check' : i===1?'clock':'file'} /></span><div><strong>{title}</strong><p>{text}</p></div></div>)}</div></div><p className="example-caption">Illustrativer Ablauf. Die passende Umsetzung richtet sich nach Ihren Systemen.</p></> : slug === 'apps-it-projekte' ? <><div className="example-toolbar"><span>Digitale Rapporterfassung</span><span className="demo-label">Demo</span></div><OrderInterface phase={choice as 0|1|2} /><div className="example-controls" role="group" aria-label="Schritt der Beispielanwendung">{['Erfassen','Prüfen','Freigeben'].map((s,i)=><button key={s} aria-pressed={choice===i} onClick={()=>setChoice(i)}><span>0{i+1}</span>{s}</button>)}</div></> : slug === 'websites' ? <WebsiteShowcase /> : <><div className="example-toolbar"><span>Was eine Betreuung umfassen kann</span><Icon name="server" /></div><div className="care-example"><h3>Ein Ansprechpartner.<br />Ein klarer Umfang.</h3>{[['Betrieb','Hosting und technische Grundlagen'],['Pflege','Updates und vereinbarte Änderungen'],['Weiterentwicklung','Neue Anforderungen gemeinsam planen']].map(([h,p])=><div key={h}><Icon name="check" /><div><strong>{h}</strong><p>{p}</p></div></div>)}<a className="text-link" href="/?leistung=betrieb-betreuung#anfrage">Betreuung besprechen <Arrow /></a></div><p className="example-caption">Der konkrete Leistungsumfang wird vor dem Start vereinbart.</p></>}
  </div>;
}
