export const offerings = [
  { slug: 'prozesse-automatisierung', name: 'Abläufe verbessern', short: 'Weniger Handarbeit. Weniger Rückfragen. Mehr Zeit fürs Geschäft.', icon: 'process', number: '01', label: 'Prozesse & Automatisierung' },
  { slug: 'apps-it-projekte', name: 'Digitale Lösungen bauen', short: 'Apps, Portale und Verbindungen zwischen Ihren Systemen.', icon: 'code', number: '02', label: 'Apps & IT-Projekte' },
  { slug: 'websites', name: 'Online überzeugen', short: 'Websites, die Ihr Angebot auf den Punkt bringen. Inklusive Betrieb.', icon: 'web', number: '03', label: 'Websites & Betrieb' },
];

export const businessWorlds = [
  { slug: 'handwerk-bau', name: 'Handwerk & Bau', fullName: 'Handwerk, Bau & Gebäudetechnik', icon: 'wrench', heading: 'Auftrag erledigt. Büroarbeit auch.', description: 'Stunden, Material und Fotos vor Ort erfassen. Im Büro direkt für die Rechnung nutzen.', task: 'Serviceauftrag', object: 'Wartung · Gebäude Nord', field: 'Arbeitszeit', value: '2.5 Std.', second: 'Material', secondValue: '1 Position', examples: ['Handwerk & Gebäudetechnik', 'Bau & Gartenbau', 'Reinigung & Hauswartung'], pains: ['Rapporte kommen spät oder unvollständig im Büro an.', 'Stunden und Material werden mehrfach übertragen.', 'Für den Auftragsstand braucht es ständig Rückfragen.'], solutions: ['Mobile Rapporte mit Zeit, Material und Fotos', 'Eine gemeinsame Einsatz- und Auftragsübersicht', 'Daten für die Abrechnung bereitstellen'], service: 'apps-it-projekte' },
  { slug: 'handel-logistik', name: 'Handel & Logistik', fullName: 'Handel & Logistik', icon: 'package', heading: 'Weniger nachfragen. Mehr bewegen.', description: 'Bestellung, Bestand und Lieferung zusammenführen. Damit Ihr Team den Stand kennt, ohne nachzufragen.', task: 'Lieferauftrag', object: 'Lieferung · Region Zürich', field: 'Positionen', value: '8 Artikel', second: 'Lieferung', secondValue: 'Bestätigt', examples: ['Gross- & Detailhandel', 'Transport & Distribution', 'Lager & Versand'], pains: ['Bestellungen werden von einem System ins andere kopiert.', 'Lieferauskünfte erfordern Telefonate und E-Mails.', 'Bestandslisten widersprechen sich.'], solutions: ['Bestell- und Wareninformationen zusammenführen', 'Auftragsstatus und Abliefernachweise digital erfassen', 'Bestehende Systeme über Schnittstellen verbinden'], service: 'prozesse-automatisierung' },
  { slug: 'dienstleistungen', name: 'Dienstleistungen', fullName: 'Dienstleistungen & Beratung', icon: 'clock', heading: 'Ihre Zeit gehört Ihren Kunden.', description: 'Anfragen, Termine und Leistungen verbinden. Damit mehr Zeit für Ihre Kunden bleibt.', task: 'Kundenprojekt', object: 'Projekt · Monatsabschluss', field: 'Zeit erfasst', value: '4.0 Std.', second: 'Freigabe', secondValue: 'Erteilt', examples: ['Beratung & Agenturen', 'Persönliche Dienstleistungen', 'Service- & Projektbetriebe'], pains: ['Kundeninformationen liegen in mehreren Postfächern.', 'Projektstände sind nur einzelnen Mitarbeitenden bekannt.', 'Leistungen werden erst Tage später nachgetragen.'], solutions: ['Anfragen, Termine und Zuständigkeiten verbinden', 'Zeiten und Leistungen direkt einem Projekt zuordnen', 'Kundenportale und passende Websites entwickeln'], service: 'apps-it-projekte' },
  { slug: 'immobilien-bewirtschaftung', name: 'Immobilien', fullName: 'Immobilien & Bewirtschaftung', icon: 'building', heading: 'Jedes Anliegen hat seinen Platz.', description: 'Meldungen und Dokumente dem richtigen Objekt zuordnen. Zuständigkeiten klären. Anliegen schneller erledigen.', task: 'Unterhaltsauftrag', object: 'Objekt · Liegenschaft Park', field: 'Meldung', value: 'Behoben', second: 'Dokumente', secondValue: 'Vollständig', examples: ['Bewirtschaftung & Verwaltung', 'Immobiliendienstleistungen', 'Facility Management'], pains: ['Meldungen kommen über Telefon, E-Mail und Chat an.', 'Dokumente und Vorgeschichten müssen gesucht werden.', 'Der Stand eines Unterhaltsauftrags ist unklar.'], solutions: ['Meldungen je Objekt erfassen und zuweisen', 'Unterhalt mit Zuständigkeiten und Status organisieren', 'Objektdokumente übersichtlich bereitstellen'], service: 'prozesse-automatisierung' },
  { slug: 'produktion-gewerbe', name: 'Produktion & Gewerbe', fullName: 'Produktion & Gewerbe', icon: 'process', heading: 'Wissen, wo der Auftrag steht.', description: 'Aufträge, Übergaben und Prüfungen verbinden. Damit der nächste Arbeitsschritt nicht auf fehlende Angaben wartet.', task: 'Fertigungsauftrag', object: 'Produktion · Serie 024', field: 'Fortschritt', value: 'Abgeschlossen', second: 'Qualität', secondValue: 'Geprüft', examples: ['Fertigung & Werkstätten', 'Verarbeitung & Montage', 'Technische Betriebe'], pains: ['Der Auftragsstand muss in der Werkstatt erfragt werden.', 'Bei Übergaben fehlen Informationen.', 'Prüfnachweise liegen auf Papier oder in einzelnen Dateien.'], solutions: ['Eine gemeinsame Übersicht für Aufträge und Arbeitsschritte', 'Digitale Übergaben und Prüfprotokolle', 'Betriebsdaten erfassen und für Entscheidungen aufbereiten'], service: 'apps-it-projekte' },
  { slug: 'weitere-betriebe', name: 'Weitere Betriebe', fullName: 'Weitere Branchen & Geschäftsmodelle', icon: 'plus', heading: 'Auch Ihr Betrieb kann mehr.', description: 'Andere Branche, gleiche Frage: Wo kostet Routine zu viel Zeit? Wir finden den Ansatz und setzen die Verbesserung um.', task: 'Betriebsablauf', object: 'Ihr Betrieb · Ihre Aufgabe', field: 'Ansatz', value: 'Festgelegt', second: 'Umsetzung', secondValue: 'Geplant', examples: ['Weitere Branchen', 'Organisationen & Vereine', 'Neue Geschäftsmodelle'], pains: ['Routineaufgaben wachsen schneller als Ihr Team.', 'Informationen werden gesucht, kopiert und nachgefragt.', 'Für Verbesserungen fehlt im Tagesgeschäft die Zeit.'], solutions: ['Wiederholungen vereinfachen oder automatisieren', 'Informationen und Zuständigkeiten zusammenführen', 'Ein Vorhaben konkret planen und gemeinsam umsetzen'], service: 'prozesse-automatisierung' },
];

export const legacyWorlds: Record<string, string> = { sanitaer: 'handwerk-bau', heizung: 'handwerk-bau', gartenbau: 'handwerk-bau', immobilien: 'immobilien-bewirtschaftung', coiffeur: 'dienstleistungen', grosshandel: 'handel-logistik', detailhandel: 'handel-logistik', transport: 'handel-logistik' };
export const enquiryTopics: Record<string, string> = { 'prozesse-automatisierung': 'Abläufe verbessern', 'apps-it-projekte': 'Apps & IT-Projekte', websites: 'Websites & Betrieb', 'betrieb-betreuung': 'Betrieb & Betreuung' };
